project:
  type: website

website:
  title: "Noah's Blog"
  favicon: "nto_icon.jpg"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/noahtolsen
      - icon: twitter-x
        href: https://twitter.com/noahtolsen
format:
  html:
    theme: cosmo
    css: styles.css



